[package]
name = "iced_music_player"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12", features = ["audio", "tokio"] }
rodio = "0.17"
rfd = "0.12"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
